# Generated by Django 3.1.6 on 2021-02-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
