# Generated by Django 3.1.6 on 2021-02-10 18:12

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210210_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='symbol',
            field=api.models.UpperCharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'symbol')},
        ),
    ]
