# Generated by Django 3.1.6 on 2021-02-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210210_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
