# Generated by Django 3.1.6 on 2021-02-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_watchlist_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
