# Generated by Django 3.1.6 on 2021-02-11 11:59

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210211_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', api.models.UpperCharField(max_length=10)),
                ('weekly_imp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('daily_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('rsi', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('false_breakout', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('perfection', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('bounce', models.BooleanField(default=False)),
                ('above_50ma', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=300)),
                ('risk', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.PositiveIntegerField()),
                ('entry', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('A_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soft_stop', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hard_stop', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breakeven', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filled', models.BooleanField(default=False)),
                ('stop_entered', models.BooleanField(default=False)),
                ('profit_taking_entered', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_bills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
