# Generated by Django 3.1.6 on 2021-02-11 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tradebill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradebill',
            name='risk',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
