# Generated by Django 3.1.6 on 2021-03-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210215_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradebill',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
