# Generated by Django 3.1.4 on 2021-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210316_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradebill',
            name='daily_channel_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
